spring:

  application:
    name: pastebin
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
logging:
  level:
    org:
      springframework:
        data:
          redis=DEBUG:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
 
  sql:
    init:
      mode: always


redis:
    host: redis.railway.internal
    port: 6379
    password: CJUxJojdezZlVVaxyUGjkVOEMtBVKVyf
server:
  port: 8080
