spring:

  application:
    name: pastebin
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
logging:
  level:
    org:
      springframework:
        data:
          redis=DEBUG:
datasource:
    url: mysql://root:ZAjMXOUyWqDiIHxReAzuiSPomTzrHtAi@mysql.railway.internal:3306/railway
    username: root
    password: ZAjMXOUyWqDiIHxReAzuiSPomTzrHtAi
    driver-class-name: com.mysql.cj.jdbc.Driver

redis:
    host: redis.railway.internal
    port: 6379
    password: CJUxJojdezZlVVaxyUGjkVOEMtBVKVyf
server:
  port: 8080
